[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["cd server && pip install -r requirements.txt"]

[phases.build]
cmds = [
    "cd server && python manage.py collectstatic --noinput",
    "cd server && python manage.py migrate --noinput"
]

[start]
cmd = "cd server && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"