[phases.setup]
nixPkgs = ["python310", "postgresql"]
aptPkgs = ["python3-pip"]

[phases.install]
cmds = ["cd server && python3 -m pip install --upgrade pip", "cd server && python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = [
    "cd server && python3 manage.py collectstatic --noinput",
    "cd server && python3 manage.py migrate --noinput"
]

[start]
cmd = "cd server && python3 -m gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"